/* apps/about.c */
extern app_st app_about;
/* apps/blackjack.c */
extern app_st app_blackjack;
/* apps/calc.c */
extern app_st app_calc;
/* apps/calendar.c */
extern app_st app_calendar;
/* apps/clock.c */
extern app_st app_clock;
/* apps/colors.c */
extern app_st app_colors;
/* apps/fonts.c */
extern app_st app_fonts;
/* apps/freecell.c */
extern app_st app_freecell;
/* apps/keys.c */
extern app_st app_keys;
/* apps/klondike.c */
extern app_st app_klondike;
/* apps/launcher.c */
extern app_st app_launcher;
/* apps/logview.c */
extern app_st app_logview;
/* apps/mahjong.c */
extern app_st app_mahjong;
/* apps/mines.c */
extern app_st app_mines;
/* apps/pairs.c */
extern app_st app_pairs;
/* apps/player.c */
extern app_st app_player;
/* apps/settings.c */
extern app_st app_settings;
/* apps/snake.c */
extern app_st app_snake;
/* apps/sounds.c */
extern app_st app_sounds;
/* apps/sudoku.c */
extern app_st app_sudoku;
/* apps/tetris.c */
extern app_st app_tetris;
